export {
  NeisClient,
  isLegacyTimetable,
  timetableKindFromSchool,
  pickSchoolRow,
  NeisDataNotFoundError,
  NeisException,
  NeisHttpException,
  type NeisClientOptions,
  type SchoolTimetableKind,
  type AcaInsTiInfoParams,
  type AcaInsTiInfoRow,
  type ClassInfoParams,
  type ClassInfoRow,
  type ElsTimetableRow,
  type HisTimetableRow,
  type MealServiceDietInfoParams,
  type MealServiceDietInfoRow,
  type MisTimetableRow,
  type SchoolInfoParams,
  type SchoolInfoRow,
  type SchoolMajorInfoParams,
  type SchoolMajorInfoRow,
  type SchoolScheduleParams,
  type SchoolScheduleRow,
  type SchulAflcoInfoParams,
  type SchulAflcoInfoRow,
  type SpsTimetableRow,
  type TiClrmInfoParams,
  type TiClrmInfoRow,
  type TimetableParams,
  type TimetableRow,
} from "./neis/index.js";

export {
  fetchTimeTable,
  fetchNeisTimeTable,
  TimetableAmbiguousSchoolError,
  TimetableError,
  TimetableInvalidWeekError,
  TimetableParseError,
  TimetableSchoolNotFoundError,
  type FetchNeisTimeTableOptions,
  type FetchTimeTableOptions,
  type Lecture,
  type TimeTableData,
  type TimeTableResult,
  type TimetableSource,
} from "./timetable/index.js";
